-- Add 80 more medicines to reach 200 total
INSERT INTO medicines (name, generic_name, manufacturer, category, form, strength, pack_size, description, requires_prescription, mrp, image_url) VALUES
-- More Cardiovascular (10)
('Diltiazem 60mg', 'Diltiazem', 'CardioHealth', 'Cardiovascular', 'tablet', '60mg', '10 tablets', 'Calcium channel blocker', true, 95.00, '/placeholder.svg?height=100&width=100'),
('Valsartan 80mg', 'Valsartan', 'CardioHealth', 'Cardiovascular', 'tablet', '80mg', '10 tablets', 'ARB for hypertension', true, 125.00, '/placeholder.svg?height=100&width=100'),
('Telmisartan 40mg', 'Telmisartan', 'CardioHealth', 'Cardiovascular', 'tablet', '40mg', '10 tablets', 'Angiotensin receptor blocker', true, 115.00, '/placeholder.svg?height=100&width=100'),
('Spironolactone 25mg', 'Spironolactone', 'CardioHealth', 'Cardiovascular', 'tablet', '25mg', '15 tablets', 'Potassium-sparing diuretic', true, 85.00, '/placeholder.svg?height=100&width=100'),
('Hydralazine 25mg', 'Hydralazine', 'CardioHealth', 'Cardiovascular', 'tablet', '25mg', '30 tablets', 'Direct vasodilator', true, 75.00, '/placeholder.svg?height=100&width=100'),
('Clonidine 0.1mg', 'Clonidine', 'CardioHealth', 'Cardiovascular', 'tablet', '0.1mg', '30 tablets', 'Central alpha agonist', true, 65.00, '/placeholder.svg?height=100&width=100'),
('Propranolol 40mg', 'Propranolol', 'CardioHealth', 'Cardiovascular', 'tablet', '40mg', '10 tablets', 'Non-selective beta blocker', true, 55.00, '/placeholder.svg?height=100&width=100'),
('Nifedipine 10mg', 'Nifedipine', 'CardioHealth', 'Cardiovascular', 'capsule', '10mg', '10 capsules', 'Calcium channel blocker', true, 45.00, '/placeholder.svg?height=100&width=100'),
('Pravastatin 20mg', 'Pravastatin', 'CardioHealth', 'Cardiovascular', 'tablet', '20mg', '10 tablets', 'Statin for cholesterol', true, 95.00, '/placeholder.svg?height=100&width=100'),
('Fenofibrate 160mg', 'Fenofibrate', 'CardioHealth', 'Cardiovascular', 'tablet', '160mg', '10 tablets', 'Fibrate for triglycerides', true, 145.00, '/placeholder.svg?height=100&width=100'),

-- More Antibiotics (10)
('Erythromycin 500mg', 'Erythromycin', 'Beta Antibiotics', 'Antibiotic', 'tablet', '500mg', '10 tablets', 'Macrolide antibiotic', true, 95.00, '/placeholder.svg?height=100&width=100'),
('Cefpodoxime 200mg', 'Cefpodoxime', 'Beta Antibiotics', 'Antibiotic', 'tablet', '200mg', '10 tablets', 'Third generation cephalosporin', true, 185.00, '/placeholder.svg?height=100&width=100'),
('Ceftriaxone 1g Injection', 'Ceftriaxone', 'Beta Antibiotics', 'Antibiotic', 'injection', '1g', '1 vial', 'Injectable cephalosporin', true, 125.00, '/placeholder.svg?height=100&width=100'),
('Clindamycin 300mg', 'Clindamycin', 'Beta Antibiotics', 'Antibiotic', 'capsule', '300mg', '10 capsules', 'Lincosamide antibiotic', true, 165.00, '/placeholder.svg?height=100&width=100'),
('Vancomycin 500mg', 'Vancomycin', 'Beta Antibiotics', 'Antibiotic', 'injection', '500mg', '1 vial', 'Glycopeptide antibiotic', true, 625.00, '/placeholder.svg?height=100&width=100'),
('Trimethoprim 200mg', 'Trimethoprim', 'Beta Antibiotics', 'Antibiotic', 'tablet', '200mg', '10 tablets', 'Folate synthesis inhibitor', true, 75.00, '/placeholder.svg?height=100&width=100'),
('Nitrofurantoin 100mg', 'Nitrofurantoin', 'Beta Antibiotics', 'Antibiotic', 'capsule', '100mg', '10 capsules', 'For urinary tract infections', true, 95.00, '/placeholder.svg?height=100&width=100'),
('Linezolid 600mg', 'Linezolid', 'Beta Antibiotics', 'Antibiotic', 'tablet', '600mg', '10 tablets', 'Oxazolidinone antibiotic', true, 985.00, '/placeholder.svg?height=100&width=100'),
('Tigecycline 50mg', 'Tigecycline', 'Beta Antibiotics', 'Antibiotic', 'injection', '50mg', '1 vial', 'Glycylcycline antibiotic', true, 1425.00, '/placeholder.svg?height=100&width=100'),
('Rifampicin 450mg', 'Rifampicin', 'Beta Antibiotics', 'Antibiotic', 'capsule', '450mg', '10 capsules', 'For tuberculosis', true, 125.00, '/placeholder.svg?height=100&width=100'),

-- More Pain Relief (10)
('Tramadol 50mg', 'Tramadol', 'PainCare', 'Pain Relief', 'capsule', '50mg', '10 capsules', 'Opioid analgesic', true, 85.00, '/placeholder.svg?height=100&width=100'),
('Morphine 10mg', 'Morphine', 'PainCare', 'Pain Relief', 'tablet', '10mg', '10 tablets', 'Opioid pain reliever', true, 225.00, '/placeholder.svg?height=100&width=100'),
('Fentanyl Patch 25mcg', 'Fentanyl', 'PainCare', 'Pain Relief', 'patch', '25mcg/hr', '5 patches', 'Transdermal opioid', true, 1245.00, '/placeholder.svg?height=100&width=100'),
('Codeine 30mg', 'Codeine', 'PainCare', 'Pain Relief', 'tablet', '30mg', '10 tablets', 'Mild opioid analgesic', true, 95.00, '/placeholder.svg?height=100&width=100'),
('Celecoxib 200mg', 'Celecoxib', 'PainCare', 'Pain Relief', 'capsule', '200mg', '10 capsules', 'COX-2 selective NSAID', true, 165.00, '/placeholder.svg?height=100&width=100'),
('Meloxicam 15mg', 'Meloxicam', 'PainCare', 'Pain Relief', 'tablet', '15mg', '10 tablets', 'NSAID for arthritis', false, 75.00, '/placeholder.svg?height=100&width=100'),
('Piroxicam 20mg', 'Piroxicam', 'PainCare', 'Pain Relief', 'capsule', '20mg', '10 capsules', 'Long-acting NSAID', true, 85.00, '/placeholder.svg?height=100&width=100'),
('Benzocaine Gel 20%', 'Benzocaine', 'PainCare', 'Pain Relief', 'gel', '20%', '15g tube', 'Topical anesthetic', false, 125.00, '/placeholder.svg?height=100&width=100'),
('Capsaicin Cream 0.075%', 'Capsaicin', 'PainCare', 'Pain Relief', 'cream', '0.075%', '30g tube', 'For muscle and joint pain', false, 185.00, '/placeholder.svg?height=100&width=100'),
('Methyl Salicylate Ointment', 'Methyl Salicylate', 'PainCare', 'Pain Relief', 'ointment', '15%', '50g tube', 'Topical pain relief', false, 95.00, '/placeholder.svg?height=100&width=100'),

-- More Digestive (10)
('Ondansetron 8mg', 'Ondansetron', 'DigestCare', 'Digestive', 'tablet', '8mg', '10 tablets', 'Anti-nausea medication', true, 145.00, '/placeholder.svg?height=100&width=100'),
('Metoclopramide 10mg', 'Metoclopramide', 'DigestCare', 'Digestive', 'tablet', '10mg', '10 tablets', 'Prokinetic antiemetic', true, 65.00, '/placeholder.svg?height=100&width=100'),
('Loperamide 2mg', 'Loperamide', 'DigestCare', 'Digestive', 'capsule', '2mg', '10 capsules', 'Anti-diarrheal', false, 55.00, '/placeholder.svg?height=100&width=100'),
('Lactulose Syrup', 'Lactulose', 'DigestCare', 'Digestive', 'syrup', '10g/15ml', '200ml bottle', 'Osmotic laxative', false, 125.00, '/placeholder.svg?height=100&width=100'),
('Bisacodyl 5mg', 'Bisacodyl', 'DigestCare', 'Digestive', 'tablet', '5mg', '10 tablets', 'Stimulant laxative', false, 45.00, '/placeholder.svg?height=100&width=100'),
('Mebeverine 135mg', 'Mebeverine', 'DigestCare', 'Digestive', 'tablet', '135mg', '10 tablets', 'Antispasmodic for IBS', false, 95.00, '/placeholder.svg?height=100&width=100'),
('Activated Charcoal 250mg', 'Activated Charcoal', 'DigestCare', 'Digestive', 'capsule', '250mg', '20 capsules', 'For gas and bloating', false, 75.00, '/placeholder.svg?height=100&width=100'),
('Simethicone 80mg', 'Simethicone', 'DigestCare', 'Digestive', 'tablet', '80mg', '20 tablets', 'Anti-gas medication', false, 65.00, '/placeholder.svg?height=100&width=100'),
('Ursodeoxycholic Acid 300mg', 'Ursodeoxycholic Acid', 'DigestCare', 'Digestive', 'capsule', '300mg', '10 capsules', 'For gallstones and liver', true, 385.00, '/placeholder.svg?height=100&width=100'),
('Mesalamine 400mg', 'Mesalamine', 'DigestCare', 'Digestive', 'tablet', '400mg', '30 tablets', 'For ulcerative colitis', true, 625.00, '/placeholder.svg?height=100&width=100'),

-- More Respiratory (10)
('Montelukast 10mg', 'Montelukast', 'BreathEasy', 'Respiratory', 'tablet', '10mg', '10 tablets', 'Leukotriene receptor antagonist', true, 185.00, '/placeholder.svg?height=100&width=100'),
('Theophylline 200mg', 'Theophylline', 'BreathEasy', 'Respiratory', 'tablet', '200mg', '10 tablets', 'Bronchodilator', true, 95.00, '/placeholder.svg?height=100&width=100'),
('Budesonide Nasal Spray', 'Budesonide', 'BreathEasy', 'Respiratory', 'spray', '64mcg', '120 doses', 'Corticosteroid for rhinitis', false, 325.00, '/placeholder.svg?height=100&width=100'),
('Fluticasone Nasal Spray', 'Fluticasone', 'BreathEasy', 'Respiratory', 'spray', '50mcg', '120 doses', 'For allergic rhinitis', false, 285.00, '/placeholder.svg?height=100&width=100'),
('Dextromethorphan 15mg', 'Dextromethorphan', 'BreathEasy', 'Respiratory', 'syrup', '15mg/5ml', '100ml bottle', 'Cough suppressant', false, 95.00, '/placeholder.svg?height=100&width=100'),
('Guaifenesin 200mg', 'Guaifenesin', 'BreathEasy', 'Respiratory', 'syrup', '200mg/10ml', '100ml bottle', 'Expectorant', false, 85.00, '/placeholder.svg?height=100&width=100'),
('Pseudoephedrine 60mg', 'Pseudoephedrine', 'BreathEasy', 'Respiratory', 'tablet', '60mg', '10 tablets', 'Decongestant', false, 75.00, '/placeholder.svg?height=100&width=100'),
('Oxymetazoline Nasal Spray', 'Oxymetazoline', 'BreathEasy', 'Respiratory', 'spray', '0.05%', '15ml bottle', 'Nasal decongestant spray', false, 95.00, '/placeholder.svg?height=100&width=100'),
('N-Acetylcysteine 600mg', 'N-Acetylcysteine', 'BreathEasy', 'Respiratory', 'tablet', '600mg', '10 tablets', 'Mucolytic agent', false, 165.00, '/placeholder.svg?height=100&width=100'),
('Tiotropium Inhaler', 'Tiotropium', 'BreathEasy', 'Respiratory', 'inhaler', '18mcg', '30 doses', 'Long-acting anticholinergic', true, 785.00, '/placeholder.svg?height=100&width=100'),

-- More Allergy (5)
('Promethazine 25mg', 'Promethazine', 'AllerCure', 'Allergy', 'tablet', '25mg', '10 tablets', 'First-generation antihistamine', true, 65.00, '/placeholder.svg?height=100&width=100'),
('Diphenhydramine 25mg', 'Diphenhydramine', 'AllerCure', 'Allergy', 'capsule', '25mg', '10 capsules', 'Antihistamine and sleep aid', false, 75.00, '/placeholder.svg?height=100&width=100'),
('Azelastine Nasal Spray', 'Azelastine', 'AllerCure', 'Allergy', 'spray', '137mcg', '30ml bottle', 'Antihistamine nasal spray', false, 425.00, '/placeholder.svg?height=100&width=100'),
('Epinephrine Auto-Injector', 'Epinephrine', 'AllerCure', 'Allergy', 'injection', '0.3mg', '1 injector', 'For anaphylaxis emergency', true, 2625.00, '/placeholder.svg?height=100&width=100'),
('Prednisolone 5mg', 'Prednisolone', 'AllerCure', 'Allergy', 'tablet', '5mg', '10 tablets', 'Corticosteroid', true, 45.00, '/placeholder.svg?height=100&width=100'),

-- More Diabetes (10)
('Pioglitazone 15mg', 'Pioglitazone', 'DiaboCure', 'Diabetes', 'tablet', '15mg', '10 tablets', 'Thiazolidinedione', true, 245.00, '/placeholder.svg?height=100&width=100'),
('Repaglinide 1mg', 'Repaglinide', 'DiaboCure', 'Diabetes', 'tablet', '1mg', '10 tablets', 'Meglitinide for diabetes', true, 185.00, '/placeholder.svg?height=100&width=100'),
('Acarbose 50mg', 'Acarbose', 'DiaboCure', 'Diabetes', 'tablet', '50mg', '10 tablets', 'Alpha-glucosidase inhibitor', true, 165.00, '/placeholder.svg?height=100&width=100'),
('Saxagliptin 5mg', 'Saxagliptin', 'DiaboCure', 'Diabetes', 'tablet', '5mg', '10 tablets', 'DPP-4 inhibitor', true, 425.00, '/placeholder.svg?height=100&width=100'),
('Empagliflozin 10mg', 'Empagliflozin', 'DiaboCure', 'Diabetes', 'tablet', '10mg', '10 tablets', 'SGLT2 inhibitor', true, 685.00, '/placeholder.svg?height=100&width=100'),
('Liraglutide Injection 6mg', 'Liraglutide', 'DiaboCure', 'Diabetes', 'injection', '6mg/ml', '3ml pen', 'GLP-1 receptor agonist', true, 3625.00, '/placeholder.svg?height=100&width=100'),
('Dulaglutide Injection', 'Dulaglutide', 'DiaboCure', 'Diabetes', 'injection', '0.75mg', '4 pens', 'Once-weekly GLP-1', true, 4825.00, '/placeholder.svg?height=100&width=100'),
('Canagliflozin 100mg', 'Canagliflozin', 'DiaboCure', 'Diabetes', 'tablet', '100mg', '10 tablets', 'SGLT2 inhibitor', true, 645.00, '/placeholder.svg?height=100&width=100'),
('Nateglinide 120mg', 'Nateglinide', 'DiaboCure', 'Diabetes', 'tablet', '120mg', '10 tablets', 'Meglitinide', true, 225.00, '/placeholder.svg?height=100&width=100'),
('Insulin Glargine 100IU', 'Insulin Glargine', 'DiaboCure', 'Diabetes', 'injection', '100IU/ml', '10ml vial', 'Long-acting insulin', true, 1825.00, '/placeholder.svg?height=100&width=100'),

-- More Neurological (10)
('Levetiracetam 500mg', 'Levetiracetam', 'NeuroCare', 'Neurological', 'tablet', '500mg', '10 tablets', 'For epilepsy', true, 185.00, '/placeholder.svg?height=100&width=100'),
('Carbamazepine 200mg', 'Carbamazepine', 'NeuroCare', 'Neurological', 'tablet', '200mg', '10 tablets', 'Anticonvulsant', true, 95.00, '/placeholder.svg?height=100&width=100'),
('Phenytoin 100mg', 'Phenytoin', 'NeuroCare', 'Neurological', 'capsule', '100mg', '10 capsules', 'For seizures', true, 75.00, '/placeholder.svg?height=100&width=100'),
('Topiramate 50mg', 'Topiramate', 'NeuroCare', 'Neurological', 'tablet', '50mg', '10 tablets', 'For epilepsy and migraines', true, 165.00, '/placeholder.svg?height=100&width=100'),
('Lamotrigine 100mg', 'Lamotrigine', 'NeuroCare', 'Neurological', 'tablet', '100mg', '10 tablets', 'Anticonvulsant', true, 225.00, '/placeholder.svg?height=100&width=100'),
('Baclofen 10mg', 'Baclofen', 'NeuroCare', 'Neurological', 'tablet', '10mg', '10 tablets', 'Muscle relaxant', true, 85.00, '/placeholder.svg?height=100&width=100'),
('Tizanidine 2mg', 'Tizanidine', 'NeuroCare', 'Neurological', 'tablet', '2mg', '10 tablets', 'Muscle relaxant', true, 95.00, '/placeholder.svg?height=100&width=100'),
('Donepezil 10mg', 'Donepezil', 'NeuroCare', 'Neurological', 'tablet', '10mg', '10 tablets', 'For Alzheimers disease', true, 425.00, '/placeholder.svg?height=100&width=100'),
('Memantine 10mg', 'Memantine', 'NeuroCare', 'Neurological', 'tablet', '10mg', '10 tablets', 'For dementia', true, 385.00, '/placeholder.svg?height=100&width=100'),
('Amantadine 100mg', 'Amantadine', 'NeuroCare', 'Neurological', 'capsule', '100mg', '10 capsules', 'For Parkinsons disease', true, 165.00, '/placeholder.svg?height=100&width=100'),

-- Vitamins & Supplements (15)
('Vitamin D3 60000 IU', 'Cholecalciferol', 'VitaCare', 'Vitamin', 'capsule', '60000 IU', '4 capsules', 'High dose vitamin D', false, 125.00, '/placeholder.svg?height=100&width=100'),
('Vitamin B12 1500mcg', 'Methylcobalamin', 'VitaCare', 'Vitamin', 'tablet', '1500mcg', '10 tablets', 'Vitamin B12 supplement', false, 95.00, '/placeholder.svg?height=100&width=100'),
('Folic Acid 5mg', 'Folic Acid', 'VitaCare', 'Vitamin', 'tablet', '5mg', '10 tablets', 'Vitamin B9 supplement', false, 45.00, '/placeholder.svg?height=100&width=100'),
('Omega-3 Fish Oil 1000mg', 'Omega-3', 'VitaCare', 'Vitamin', 'capsule', '1000mg', '30 capsules', 'EPA and DHA supplement', false, 425.00, '/placeholder.svg?height=100&width=100'),
('Multivitamin Complete', 'Multivitamin', 'VitaCare', 'Vitamin', 'tablet', 'Multi', '30 tablets', 'Complete vitamin formula', false, 285.00, '/placeholder.svg?height=100&width=100'),
('Vitamin E 400 IU', 'Tocopherol', 'VitaCare', 'Vitamin', 'capsule', '400 IU', '10 capsules', 'Antioxidant vitamin', false, 165.00, '/placeholder.svg?height=100&width=100'),
('Biotin 10000mcg', 'Biotin', 'VitaCare', 'Vitamin', 'tablet', '10000mcg', '30 tablets', 'For hair and skin', false, 425.00, '/placeholder.svg?height=100&width=100'),
('Zinc Gluconate 50mg', 'Zinc', 'VitaCare', 'Vitamin', 'tablet', '50mg', '30 tablets', 'Immune support', false, 185.00, '/placeholder.svg?height=100&width=100'),
('Magnesium Citrate 200mg', 'Magnesium', 'VitaCare', 'Vitamin', 'tablet', '200mg', '30 tablets', 'Magnesium supplement', false, 225.00, '/placeholder.svg?height=100&width=100'),
('Calcium Carbonate 500mg', 'Calcium', 'VitaCare', 'Vitamin', 'tablet', '500mg', '30 tablets', 'Bone health support', false, 165.00, '/placeholder.svg?height=100&width=100'),
('Iron Ferrous Sulfate 65mg', 'Iron', 'VitaCare', 'Vitamin', 'tablet', '65mg', '30 tablets', 'For anemia', false, 95.00, '/placeholder.svg?height=100&width=100'),
('Coenzyme Q10 100mg', 'CoQ10', 'VitaCare', 'Vitamin', 'capsule', '100mg', '30 capsules', 'Heart health support', false, 625.00, '/placeholder.svg?height=100&width=100'),
('Glucosamine 1500mg', 'Glucosamine', 'VitaCare', 'Vitamin', 'tablet', '1500mg', '30 tablets', 'Joint health support', false, 525.00, '/placeholder.svg?height=100&width=100'),
('Probiotics 10 Billion CFU', 'Probiotics', 'VitaCare', 'Vitamin', 'capsule', '10B CFU', '30 capsules', 'Gut health support', false, 625.00, '/placeholder.svg?height=100&width=100'),
('Turmeric Curcumin 500mg', 'Curcumin', 'VitaCare', 'Vitamin', 'capsule', '500mg', '30 capsules', 'Anti-inflammatory', false, 425.00, '/placeholder.svg?height=100&width=100');
